### ISSUE TITLE
Add version number to commit message from pr-bumper that indicates was an automated version bump

### ISSUE THREAD

**Issue by notmessenger** [ciena-blueplanet/pr-bumper#118]

**Comment by job13er** [comment]
So, instead of:

```
[pr-bumper] Automated version bump
```
You want to see:

```
[pr-bumper] Automated version bump to v1.2.3
```
??

I'm fine with that, go for it: https://github.com/ciena-blueplanet/pr-bumper/blob/076fdbf97b2f04371a1c49bb11d9451eb864a5c7/lib/bumper.js#L346-L353

I believe that `info` object has the new version:
https://github.com/ciena-blueplanet/pr-bumper/blob/076fdbf97b2f04371a1c49bb11d9451eb864a5c7/lib/typedefs.js#L221

**Comment by job13er** [comment]
Wow, github renders code you link to? Awesome!

**Comment by notmessenger** [comment]
Yes that is what I am proposing.  Will get it put in.

And that code thing is pretty sweet!
