### ISSUE TITLE
PROPOSAL: Capture information during the bump process and make it available to other processes

### ISSUE THREAD

**Issue by notmessenger** [ciena-blueplanet/pr-bumper#125]
While a new PR is being released information such as the version, scope, changelog, etc is gathered by `pr-bumper`.  I propose that as this information is gathered it is held onto until completion of publishing and then it makes it available as an object on an environment variable.   This way other process running in the CI environment can then utilize this information without have to obtain it on their own.

**Comment by job13er** [comment]
I like the idea, only one small issue, `pr-bumper` doesn't do publishing. Do you mean the commit that's pushed with the changes? If that's what you consider publishing, then yeah, sounds good. I'd suggest a `.json` file with the info, rather than an environment variable as those don't always persist between steps in a CI.
