### ISSUE TITLE
Support configuration to allow non-publishing branches for development work

### ISSUE THREAD

**Issue by sglanzer** [ciena-blueplanet/pr-bumper#40]
I'd like the ability to specify branches in a configuration file that are excluded from the bumper checks so that work can be done in a public branch without publishing.

**Comment by job13er** [comment]
Just to clarify `pr-bumper` doesn't control what's published, it's normally wired into `before_deploy` in travis and runs just prior to publishing. So the `bump` command you wire in probably won't run if your CI is properly configured to not deploy that branch.

As for the `check` command, that could probably use some kind of configuration to tell it to not do the check for PRs targeted at a particular branch (or branches). Seems kinda related to #39 I was tempted to do some inspection of the target branch and only allow something like `master` and ones that fit the `1.x` pattern, but that seems unnecessarily restrictive. 

I suppose if it were configured on a branch basis, it would be safe for the `check` command to ignore the PR since the `bump` command (even if it was somehow running) would also ignore it. 

So, kind of a long-winded way of saying, "Sure. we can do that, just be careful because this change alone won't actually prevent that branch from being published. It'll only prevent it from being bumped"

**Comment by sglanzer** [comment]
I'd be in support of a `master` and `1.x` convention - I like conventions ;)

**Comment by job13er** [comment]
I suppose that could be easily configurable, with a regex, etc.

**Comment by job13er** [comment]
I'll probably work that in, with a name for a `main` branch (default `master`) where `MAJOR` bumps are allowed, and a regex for `maintenance` branches (default `^[0-9]+.x$`) and all other branches are skipped.

**Comment by job13er** [comment]
@sglanzer Would the existing support for `#none#` achieve what this is asking for? If so, can we close this?

**Comment by sglanzer** [comment]
Yeah, I think for this particular case `#none#` covers it (assuming every PR to that branch is given `#none`)
