### ISSUE TITLE
[Discussion] Should there be a `#none#` directive?

### ISSUE THREAD

**Issue by zakhenry** [ciena-blueplanet/pr-bumper#49]
Not sure of the actual keyword, but I was wondering if it would be a good idea to have support for a directive that passes the validation, but does not cause a version bump.

The rationale behind this is that sometimes there may be some changes to a package that result in no code change at all (files that are never pushed to an npm registry). An example would be changes to documentation files that are `.npmignore`d. Or changes to the `.travis.yml` file.

Normally I would just issue a `#patch#` change, but this is somewhat problematic when integrating with dependency updating like https://greenkeeper.io or https://gemnasium.com as they will report that an update needs to be made, _despite the package having no relevant changes_.

I'm on the fence with what is the right answer, so interested to see what others think.

**Comment by job13er** [comment]
We've considered this, but haven't implemented it as of yet because there are implications outside of `pr-bumper` Our workflow automatically publishes to `npm` on every successful pr merge. That is something we don't necessarily want to lose. Of course, it does that last, so failing to publish because that version was already published is an option, but doesn't seem a particularly compelling one to me, as that would mean the happy path includes a failed merge build. If that becomes the norm, then tests can start failing without people noticing. 

There can probably be some mechanism where we let `pr-bumper` perform a check as to whether or not the build should be published, and skip that altogether when only documentation or dev dependencies are changed. Something like increasing test coverage, if no actual code under test was modified, is another good example of a change that doesn't really warrant publishing a new version.

**Comment by zakhenry** [comment]
Yes good points about there being complexity in skipping the publish when it is not needed. It could be as simple as pr-bumper exporting a env var like `VERSION_BUMP=true` and the deployment is conditional:

```yml
deploy:
  provider: npm
  email: zak@ubiquits.com
  skip_cleanup: true
  api_key:
    secure: [...]
  on:
    branch: master
    tags: false
    condition: $VERSION_BUMP = true
```
